import type { BaseContract, BigNumber, BytesLike, CallOverrides, ContractTransaction, Overrides, PopulatedTransaction, Signer, utils, providers } from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../common.js";
export interface FeeInterface extends utils.Interface {
    functions: {
        "creationFee()": FunctionFragment;
        "feeCollectorAddress()": FunctionFragment;
        "getChainId()": FunctionFragment;
        "getCreationFee()": FunctionFragment;
        "getCreationFeeARB()": FunctionFragment;
        "getCreationFeeETH()": FunctionFragment;
        "getCreationFeeTezos()": FunctionFragment;
        "getCreationFeeUSDC()": FunctionFragment;
        "getCreationFeeXFI()": FunctionFragment;
        "getFeeCollectorAddress()": FunctionFragment;
        "getPriceInfo()": FunctionFragment;
        "getTransactionFee()": FunctionFragment;
        "getTransactionFeeETH()": FunctionFragment;
        "getTransactionFeeTezos()": FunctionFragment;
        "getTransactionFeeXFI()": FunctionFragment;
        "latestPrice()": FunctionFragment;
        "requiredValueInWei()": FunctionFragment;
        "timestampOflatestPrice()": FunctionFragment;
        "transactionFee()": FunctionFragment;
    };
    getFunction(nameOrSignatureOrTopic: "creationFee" | "creationFee()" | "feeCollectorAddress" | "feeCollectorAddress()" | "getChainId" | "getChainId()" | "getCreationFee" | "getCreationFee()" | "getCreationFeeARB" | "getCreationFeeARB()" | "getCreationFeeETH" | "getCreationFeeETH()" | "getCreationFeeTezos" | "getCreationFeeTezos()" | "getCreationFeeUSDC" | "getCreationFeeUSDC()" | "getCreationFeeXFI" | "getCreationFeeXFI()" | "getFeeCollectorAddress" | "getFeeCollectorAddress()" | "getPriceInfo" | "getPriceInfo()" | "getTransactionFee" | "getTransactionFee()" | "getTransactionFeeETH" | "getTransactionFeeETH()" | "getTransactionFeeTezos" | "getTransactionFeeTezos()" | "getTransactionFeeXFI" | "getTransactionFeeXFI()" | "latestPrice" | "latestPrice()" | "requiredValueInWei" | "requiredValueInWei()" | "timestampOflatestPrice" | "timestampOflatestPrice()" | "transactionFee" | "transactionFee()"): FunctionFragment;
    encodeFunctionData(functionFragment: "creationFee", values?: undefined): string;
    encodeFunctionData(functionFragment: "creationFee()", values?: undefined): string;
    encodeFunctionData(functionFragment: "feeCollectorAddress", values?: undefined): string;
    encodeFunctionData(functionFragment: "feeCollectorAddress()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getChainId", values?: undefined): string;
    encodeFunctionData(functionFragment: "getChainId()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFee", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFee()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFeeARB", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFeeARB()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFeeETH", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFeeETH()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFeeTezos", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFeeTezos()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFeeUSDC", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFeeUSDC()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFeeXFI", values?: undefined): string;
    encodeFunctionData(functionFragment: "getCreationFeeXFI()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getFeeCollectorAddress", values?: undefined): string;
    encodeFunctionData(functionFragment: "getFeeCollectorAddress()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getPriceInfo", values?: undefined): string;
    encodeFunctionData(functionFragment: "getPriceInfo()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getTransactionFee", values?: undefined): string;
    encodeFunctionData(functionFragment: "getTransactionFee()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getTransactionFeeETH", values?: undefined): string;
    encodeFunctionData(functionFragment: "getTransactionFeeETH()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getTransactionFeeTezos", values?: undefined): string;
    encodeFunctionData(functionFragment: "getTransactionFeeTezos()", values?: undefined): string;
    encodeFunctionData(functionFragment: "getTransactionFeeXFI", values?: undefined): string;
    encodeFunctionData(functionFragment: "getTransactionFeeXFI()", values?: undefined): string;
    encodeFunctionData(functionFragment: "latestPrice", values?: undefined): string;
    encodeFunctionData(functionFragment: "latestPrice()", values?: undefined): string;
    encodeFunctionData(functionFragment: "requiredValueInWei", values?: undefined): string;
    encodeFunctionData(functionFragment: "requiredValueInWei()", values?: undefined): string;
    encodeFunctionData(functionFragment: "timestampOflatestPrice", values?: undefined): string;
    encodeFunctionData(functionFragment: "timestampOflatestPrice()", values?: undefined): string;
    encodeFunctionData(functionFragment: "transactionFee", values?: undefined): string;
    encodeFunctionData(functionFragment: "transactionFee()", values?: undefined): string;
    decodeFunctionResult(functionFragment: "creationFee", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "creationFee()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "feeCollectorAddress", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "feeCollectorAddress()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getChainId", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getChainId()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFee", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFee()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFeeARB", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFeeARB()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFeeETH", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFeeETH()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFeeTezos", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFeeTezos()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFeeUSDC", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFeeUSDC()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFeeXFI", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getCreationFeeXFI()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getFeeCollectorAddress", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getFeeCollectorAddress()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getPriceInfo", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getPriceInfo()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getTransactionFee", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getTransactionFee()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getTransactionFeeETH", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getTransactionFeeETH()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getTransactionFeeTezos", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getTransactionFeeTezos()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getTransactionFeeXFI", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getTransactionFeeXFI()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "latestPrice", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "latestPrice()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "requiredValueInWei", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "requiredValueInWei()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "timestampOflatestPrice", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "timestampOflatestPrice()", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "transactionFee", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "transactionFee()", data: BytesLike): Result;
    events: {};
}
export interface Fee extends BaseContract {
    connect(signerOrProvider: Signer | providers.Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;
    interface: FeeInterface;
    queryFilter<TEvent extends TypedEvent>(event: TypedEventFilter<TEvent>, fromBlockOrBlockhash?: string | number | undefined, toBlock?: string | number | undefined): Promise<Array<TEvent>>;
    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
    listeners(eventName?: string): Array<providers.Listener>;
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
    removeAllListeners(eventName?: string): this;
    off: OnEvent<this>;
    on: OnEvent<this>;
    once: OnEvent<this>;
    removeListener: OnEvent<this>;
    functions: {
        creationFee(overrides?: CallOverrides): Promise<[BigNumber]>;
        "creationFee()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        feeCollectorAddress(overrides?: CallOverrides): Promise<[string]>;
        "feeCollectorAddress()"(overrides?: CallOverrides): Promise<[string]>;
        getChainId(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getChainId()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        getCreationFee(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getCreationFee()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        getCreationFeeARB(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getCreationFeeARB()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        getCreationFeeETH(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getCreationFeeETH()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        getCreationFeeTezos(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getCreationFeeTezos()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        getCreationFeeUSDC(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getCreationFeeUSDC()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        getCreationFeeXFI(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getCreationFeeXFI()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        getFeeCollectorAddress(overrides?: CallOverrides): Promise<[string]>;
        "getFeeCollectorAddress()"(overrides?: CallOverrides): Promise<[string]>;
        getPriceInfo(overrides?: Overrides & {
            from?: PromiseOrValue<string>;
        }): Promise<ContractTransaction>;
        "getPriceInfo()"(overrides?: Overrides & {
            from?: PromiseOrValue<string>;
        }): Promise<ContractTransaction>;
        getTransactionFee(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getTransactionFee()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        getTransactionFeeETH(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getTransactionFeeETH()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        getTransactionFeeTezos(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getTransactionFeeTezos()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        getTransactionFeeXFI(overrides?: CallOverrides): Promise<[BigNumber]>;
        "getTransactionFeeXFI()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        latestPrice(overrides?: CallOverrides): Promise<[BigNumber]>;
        "latestPrice()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        requiredValueInWei(overrides?: CallOverrides): Promise<[BigNumber]>;
        "requiredValueInWei()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        timestampOflatestPrice(overrides?: CallOverrides): Promise<[BigNumber]>;
        "timestampOflatestPrice()"(overrides?: CallOverrides): Promise<[BigNumber]>;
        transactionFee(overrides?: CallOverrides): Promise<[BigNumber]>;
        "transactionFee()"(overrides?: CallOverrides): Promise<[BigNumber]>;
    };
    creationFee(overrides?: CallOverrides): Promise<BigNumber>;
    "creationFee()"(overrides?: CallOverrides): Promise<BigNumber>;
    feeCollectorAddress(overrides?: CallOverrides): Promise<string>;
    "feeCollectorAddress()"(overrides?: CallOverrides): Promise<string>;
    getChainId(overrides?: CallOverrides): Promise<BigNumber>;
    "getChainId()"(overrides?: CallOverrides): Promise<BigNumber>;
    getCreationFee(overrides?: CallOverrides): Promise<BigNumber>;
    "getCreationFee()"(overrides?: CallOverrides): Promise<BigNumber>;
    getCreationFeeARB(overrides?: CallOverrides): Promise<BigNumber>;
    "getCreationFeeARB()"(overrides?: CallOverrides): Promise<BigNumber>;
    getCreationFeeETH(overrides?: CallOverrides): Promise<BigNumber>;
    "getCreationFeeETH()"(overrides?: CallOverrides): Promise<BigNumber>;
    getCreationFeeTezos(overrides?: CallOverrides): Promise<BigNumber>;
    "getCreationFeeTezos()"(overrides?: CallOverrides): Promise<BigNumber>;
    getCreationFeeUSDC(overrides?: CallOverrides): Promise<BigNumber>;
    "getCreationFeeUSDC()"(overrides?: CallOverrides): Promise<BigNumber>;
    getCreationFeeXFI(overrides?: CallOverrides): Promise<BigNumber>;
    "getCreationFeeXFI()"(overrides?: CallOverrides): Promise<BigNumber>;
    getFeeCollectorAddress(overrides?: CallOverrides): Promise<string>;
    "getFeeCollectorAddress()"(overrides?: CallOverrides): Promise<string>;
    getPriceInfo(overrides?: Overrides & {
        from?: PromiseOrValue<string>;
    }): Promise<ContractTransaction>;
    "getPriceInfo()"(overrides?: Overrides & {
        from?: PromiseOrValue<string>;
    }): Promise<ContractTransaction>;
    getTransactionFee(overrides?: CallOverrides): Promise<BigNumber>;
    "getTransactionFee()"(overrides?: CallOverrides): Promise<BigNumber>;
    getTransactionFeeETH(overrides?: CallOverrides): Promise<BigNumber>;
    "getTransactionFeeETH()"(overrides?: CallOverrides): Promise<BigNumber>;
    getTransactionFeeTezos(overrides?: CallOverrides): Promise<BigNumber>;
    "getTransactionFeeTezos()"(overrides?: CallOverrides): Promise<BigNumber>;
    getTransactionFeeXFI(overrides?: CallOverrides): Promise<BigNumber>;
    "getTransactionFeeXFI()"(overrides?: CallOverrides): Promise<BigNumber>;
    latestPrice(overrides?: CallOverrides): Promise<BigNumber>;
    "latestPrice()"(overrides?: CallOverrides): Promise<BigNumber>;
    requiredValueInWei(overrides?: CallOverrides): Promise<BigNumber>;
    "requiredValueInWei()"(overrides?: CallOverrides): Promise<BigNumber>;
    timestampOflatestPrice(overrides?: CallOverrides): Promise<BigNumber>;
    "timestampOflatestPrice()"(overrides?: CallOverrides): Promise<BigNumber>;
    transactionFee(overrides?: CallOverrides): Promise<BigNumber>;
    "transactionFee()"(overrides?: CallOverrides): Promise<BigNumber>;
    callStatic: {
        creationFee(overrides?: CallOverrides): Promise<BigNumber>;
        "creationFee()"(overrides?: CallOverrides): Promise<BigNumber>;
        feeCollectorAddress(overrides?: CallOverrides): Promise<string>;
        "feeCollectorAddress()"(overrides?: CallOverrides): Promise<string>;
        getChainId(overrides?: CallOverrides): Promise<BigNumber>;
        "getChainId()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFee(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFee()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFeeARB(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFeeARB()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFeeETH(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFeeETH()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFeeTezos(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFeeTezos()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFeeUSDC(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFeeUSDC()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFeeXFI(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFeeXFI()"(overrides?: CallOverrides): Promise<BigNumber>;
        getFeeCollectorAddress(overrides?: CallOverrides): Promise<string>;
        "getFeeCollectorAddress()"(overrides?: CallOverrides): Promise<string>;
        getPriceInfo(overrides?: CallOverrides): Promise<void>;
        "getPriceInfo()"(overrides?: CallOverrides): Promise<void>;
        getTransactionFee(overrides?: CallOverrides): Promise<BigNumber>;
        "getTransactionFee()"(overrides?: CallOverrides): Promise<BigNumber>;
        getTransactionFeeETH(overrides?: CallOverrides): Promise<BigNumber>;
        "getTransactionFeeETH()"(overrides?: CallOverrides): Promise<BigNumber>;
        getTransactionFeeTezos(overrides?: CallOverrides): Promise<BigNumber>;
        "getTransactionFeeTezos()"(overrides?: CallOverrides): Promise<BigNumber>;
        getTransactionFeeXFI(overrides?: CallOverrides): Promise<BigNumber>;
        "getTransactionFeeXFI()"(overrides?: CallOverrides): Promise<BigNumber>;
        latestPrice(overrides?: CallOverrides): Promise<BigNumber>;
        "latestPrice()"(overrides?: CallOverrides): Promise<BigNumber>;
        requiredValueInWei(overrides?: CallOverrides): Promise<BigNumber>;
        "requiredValueInWei()"(overrides?: CallOverrides): Promise<BigNumber>;
        timestampOflatestPrice(overrides?: CallOverrides): Promise<BigNumber>;
        "timestampOflatestPrice()"(overrides?: CallOverrides): Promise<BigNumber>;
        transactionFee(overrides?: CallOverrides): Promise<BigNumber>;
        "transactionFee()"(overrides?: CallOverrides): Promise<BigNumber>;
    };
    filters: {};
    estimateGas: {
        creationFee(overrides?: CallOverrides): Promise<BigNumber>;
        "creationFee()"(overrides?: CallOverrides): Promise<BigNumber>;
        feeCollectorAddress(overrides?: CallOverrides): Promise<BigNumber>;
        "feeCollectorAddress()"(overrides?: CallOverrides): Promise<BigNumber>;
        getChainId(overrides?: CallOverrides): Promise<BigNumber>;
        "getChainId()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFee(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFee()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFeeARB(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFeeARB()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFeeETH(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFeeETH()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFeeTezos(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFeeTezos()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFeeUSDC(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFeeUSDC()"(overrides?: CallOverrides): Promise<BigNumber>;
        getCreationFeeXFI(overrides?: CallOverrides): Promise<BigNumber>;
        "getCreationFeeXFI()"(overrides?: CallOverrides): Promise<BigNumber>;
        getFeeCollectorAddress(overrides?: CallOverrides): Promise<BigNumber>;
        "getFeeCollectorAddress()"(overrides?: CallOverrides): Promise<BigNumber>;
        getPriceInfo(overrides?: Overrides & {
            from?: PromiseOrValue<string>;
        }): Promise<BigNumber>;
        "getPriceInfo()"(overrides?: Overrides & {
            from?: PromiseOrValue<string>;
        }): Promise<BigNumber>;
        getTransactionFee(overrides?: CallOverrides): Promise<BigNumber>;
        "getTransactionFee()"(overrides?: CallOverrides): Promise<BigNumber>;
        getTransactionFeeETH(overrides?: CallOverrides): Promise<BigNumber>;
        "getTransactionFeeETH()"(overrides?: CallOverrides): Promise<BigNumber>;
        getTransactionFeeTezos(overrides?: CallOverrides): Promise<BigNumber>;
        "getTransactionFeeTezos()"(overrides?: CallOverrides): Promise<BigNumber>;
        getTransactionFeeXFI(overrides?: CallOverrides): Promise<BigNumber>;
        "getTransactionFeeXFI()"(overrides?: CallOverrides): Promise<BigNumber>;
        latestPrice(overrides?: CallOverrides): Promise<BigNumber>;
        "latestPrice()"(overrides?: CallOverrides): Promise<BigNumber>;
        requiredValueInWei(overrides?: CallOverrides): Promise<BigNumber>;
        "requiredValueInWei()"(overrides?: CallOverrides): Promise<BigNumber>;
        timestampOflatestPrice(overrides?: CallOverrides): Promise<BigNumber>;
        "timestampOflatestPrice()"(overrides?: CallOverrides): Promise<BigNumber>;
        transactionFee(overrides?: CallOverrides): Promise<BigNumber>;
        "transactionFee()"(overrides?: CallOverrides): Promise<BigNumber>;
    };
    populateTransaction: {
        creationFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "creationFee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        feeCollectorAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "feeCollectorAddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getChainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getChainId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getCreationFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getCreationFee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getCreationFeeARB(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getCreationFeeARB()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getCreationFeeETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getCreationFeeETH()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getCreationFeeTezos(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getCreationFeeTezos()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getCreationFeeUSDC(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getCreationFeeUSDC()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getCreationFeeXFI(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getCreationFeeXFI()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getFeeCollectorAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getFeeCollectorAddress()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getPriceInfo(overrides?: Overrides & {
            from?: PromiseOrValue<string>;
        }): Promise<PopulatedTransaction>;
        "getPriceInfo()"(overrides?: Overrides & {
            from?: PromiseOrValue<string>;
        }): Promise<PopulatedTransaction>;
        getTransactionFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getTransactionFee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getTransactionFeeETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getTransactionFeeETH()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getTransactionFeeTezos(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getTransactionFeeTezos()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        getTransactionFeeXFI(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "getTransactionFeeXFI()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        latestPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "latestPrice()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        requiredValueInWei(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "requiredValueInWei()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        timestampOflatestPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "timestampOflatestPrice()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        transactionFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;
        "transactionFee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
    };
}
